services:
  mongodb:
    image: mongo:7
    container_name: trainer-workload-mongodb
    environment:
      MONGO_INITDB_DATABASE: trainer-workload
    ports:
      - '27017:27017'
    volumes:
      - trainer_workload_mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  activemq:
    image: apache/activemq-classic:6.1.6
    container_name: gym-crm-activemq
    ports:
      - "61616:61616"
      - "8161:8161"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --user=admin --password=admin http://localhost:8161/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  trainer_workload_mongo_data:
