server:
  port: 8082

spring:
  application:
    name: trainer-workload-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/trainer-workload}
    username: ${DB_USERNAME:workload_user}
    password: ${DB_PASSWORD:workload_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
      jakarta:
        persistence:
          validation:
            mode: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

security:
  service:
    secret: ${SERVICE_JWT_SERVICE:local-only-dev-shared-secret-key-not-for-prod-use-1234567890}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
